CREATE TABLE client
  (
     id                 bigint generated by default as identity NOT NULL,
     created_at         timestamp NOT NULL,
     updated_at         timestamp NOT NULL,
     first_name         VARCHAR(255),
     last_name          VARCHAR(255),
     date_of_birth      date,
     email_address      VARCHAR(255),
     mobile_number      VARCHAR(255),
     physical_address   VARCHAR(255),
     status             VARCHAR(255),
     PRIMARY KEY (id)
  );

CREATE TABLE product
  (
     id                 bigint generated by default as identity NOT NULL,
     created_at         timestamp NOT NULL,
     updated_at         timestamp NOT NULL,
     name               VARCHAR(255),
     product_type       VARCHAR(255),
     current_balance    double precision,
     client_id           bigint,
     PRIMARY KEY (id),
     CONSTRAINT fk_product_client
     FOREIGN KEY(client_id)
     REFERENCES client(id)
  );

  CREATE TABLE withdrawal
  (
    id                 bigint generated by default as identity NOT NULL,
    created_at         timestamp NOT NULL,
    updated_at         timestamp NOT NULL,
    amount             double precision,
    product_id          bigint,
    status             VARCHAR(255),
    PRIMARY KEY (id),
    CONSTRAINT fk_withdrawal_product
    FOREIGN KEY(product_id)
    REFERENCES product(id)
  );